from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(685, 538)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.incomming_message_text = QtWidgets.QLineEdit(self.widget)
        self.incomming_message_text.setObjectName("incomming_message_text")
        self.horizontalLayout.addWidget(self.incomming_message_text)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.regex_text = QtWidgets.QLineEdit(self.widget_2)
        self.regex_text.setObjectName("regex_text")
        self.horizontalLayout_2.addWidget(self.regex_text)
        self.verticalLayout.addWidget(self.widget_2)
        self.case_sensitive_checkbox = QtWidgets.QCheckBox(self.widget_3)
        self.case_sensitive_checkbox.setObjectName("case_sensitive_checkbox")
        self.verticalLayout.addWidget(self.case_sensitive_checkbox, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(Dialog)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.replymessage_textarea = QtWidgets.QPlainTextEdit(self.widget_4)
        self.replymessage_textarea.setObjectName("replymessage_textarea")
        self.verticalLayout_2.addWidget(self.replymessage_textarea)
        self.error = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error.sizePolicy().hasHeightForWidth())
        self.error.setSizePolicy(sizePolicy)
        self.error.setText("")
        self.error.setObjectName("error")
        self.verticalLayout_2.addWidget(self.error)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(Dialog)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dialog_cancel_btn = QtWidgets.QPushButton(self.widget_5)
        self.dialog_cancel_btn.setObjectName("dialog_cancel_btn")
        self.horizontalLayout_3.addWidget(self.dialog_cancel_btn)
        self.dialog_save_btn = QtWidgets.QPushButton(self.widget_5)
        self.dialog_save_btn.setObjectName("dialog_save_btn")
        self.horizontalLayout_3.addWidget(self.dialog_save_btn)
        self.verticalLayout_3.addWidget(self.widget_5, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Reply"))
        self.label.setText(_translate("Dialog", "Incomming Message"))
        self.label_4.setText(_translate("Dialog", "Regex (Advance)"))
        self.case_sensitive_checkbox.setText(_translate("Dialog", "Case Sensitive"))
        self.label_3.setText(_translate("Dialog", "Reply"))
        self.replymessage_textarea.setPlaceholderText(_translate("Dialog", "Reply Message"))
        self.dialog_cancel_btn.setText(_translate("Dialog", "Cancel"))
        self.dialog_save_btn.setText(_translate("Dialog", "Save"))
